server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: echo_app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: go-grafana-logs
          __path__: /app/logs/*.log

    pipeline_stages:
      - json:
          expressions:
            status: status
            path: path

      - drop:
          source: path
          expression: "^/(metrics|health)$"

      - drop:
          source: status
          expression: "^[23][0-9]{2}$"


